// log-model.js — PURE data model for the production log (no DOM, no Firebase, no
// storage), so the whole thing is unit-testable in isolation (P15 — the owner
// cannot read code).
//
// THE MODEL (Block 1 of the log refactor)
// Each log is its OWN document, so two logs of the same dough on the same day no
// longer overwrite each other (the old model stored one document per dough type).
// A log keeps an APPEND-ONLY chain of versions: editing never destroys the previous
// version, and restoring an old version appends a copy on top — the chain is never
// truncated or overwritten. The latest version is simply the last element.
//
//   log = {
//     id,                         // unique id (generated by the caller)
//     bakery: 'main',             // discriminator, like the rest of the app
//     dough: 'Focaccia'|'Brioche'|'Sourdough',
//     forDay: 'today'|'tomorrow', // chosen at creation (A)
//     origin: 'calculator'|'manual', // where it was made: a calculator Confirm, or
//                                 // a manual "+ Add log". Only manual logs can be
//                                 // edited from the Log screen; calculator logs are
//                                 // edited only from the calculator (Edit → Confirm).
//     createdAtMs,                // for stable ordering (passed in by the caller)
//     versions: [ version, ... ], // append-only; versions[last] is the latest
//   }
//
//   version = {
//     calculatedBy,               // free-typed name (no identity system — Block 1)
//     at: { date, time },         // when this version was made (logTimestamp)
//     kind: 'create'|'edit'|'restore',
//     restoredFrom,               // index restored from, for 'restore' versions
//     items: [ line, ... ],       // editable order content (quantities)
//     occasional: [ occ, ... ],   // occasional clients that live ONLY in this log
//     sheet,                       // snapshot of the calculator sheet (read-only view)
//     legacy,                      // true for a migrated old-model record (text only)
//     text,                        // human-readable grouped text (share / legacy)
//   }
//
//   line = { id, name, clientName, qty, weightG, kind, crate, source }
//     source: 'client' (a configured category product) | 'occasional'
//   occ  = { name, products: [ { name, qty, weightG, unit } ] }

import { scaleRecipe } from './calculator-dough-math.js';
import { recipeSpec } from './calculator-config.js';

export const FOR_DAYS = ['today', 'tomorrow'];

// Deep clone of plain data (no functions/dates), used to keep callers from mutating
// shared version objects when appending or restoring.
function clone(v) { return JSON.parse(JSON.stringify(v)); }

const num = (v) => { const n = Number(v); return Number.isFinite(n) ? n : 0; };

// A recipe's display name for a log. Any non-empty string is kept (recipes are now
// arbitrary, no fixed enum); blank falls back to a generic label.
function safeDough(d) { const s = String(d == null ? '' : d).trim(); return s || 'Recipe'; }
function safeForDay(d) { return FOR_DAYS.includes(d) ? d : 'today'; }

// ── Sheet math (pure) ─────────────────────────────────────────────────────────
// Build the calculator-sheet snapshot from a flat list of order lines, the recipe
// and the dough parameter. total raw grams = Σ qty×weightG over all lines + extra;
// the recipe is then scaled to that total with the existing dough math, so the
// stored sheet is faithful and independent of any later recipe/config change.
//   items: [{ id, name, qty, weightG, kind, crate }]
//   divisor: { includedIds: [...], n: 0..4 }  (optional, display-only crate split)
// `recipe` is the CONFIG recipe (id, name, logic, ingredients[{key,label,grams}],
// leaveningKey, leaveningDefaultPct, baselinePct). The target is computed by the
// recipe's logic (orders → items + extra; total → typed total; both → items + total
// + extra), then the recipe is scaled to it with the unified scaleRecipe — so the
// stored sheet is faithful and independent of any later config change.
//   items:   [{ id, name, clientName, qty, weightG, kind, crate }]
//   divisor: { includedIds: [...], n: 0..4 }  (optional, display-only crate split)
export function buildSheet({ recipe, items, extraGrams = 0, totalInput = 0, leaveningPct, divisor }) {
  const lines = Array.isArray(items) ? items : [];
  const productsTotal = lines.reduce((s, it) => s + num(it.qty) * num(it.weightG), 0);
  const extra = Math.max(0, num(extraGrams));
  const typed = Math.max(0, num(totalInput));
  const logic = (recipe && recipe.logic) || 'orders';
  const total = logic === 'total' ? typed
    : logic === 'both' ? (productsTotal + typed + extra)
    : (productsTotal + extra);

  const recipeIngs = (recipe && Array.isArray(recipe.ingredients)) ? recipe.ingredients : [];
  const pct = Number.isFinite(Number(leaveningPct)) ? Number(leaveningPct) : (recipe ? num(recipe.leaveningDefaultPct) : 0);
  const spec = recipeSpec(recipe || {});
  if (logic === 'total') spec.leaveningKey = null; // pure pro-rata
  let amounts = [];
  if (total > 0 && recipeIngs.length) amounts = scaleRecipe(spec, total, pct);
  const ingredients = recipeIngs.map((ing, i) => ({ name: ing.label, grams: Math.round(num(amounts[i])) }));

  // The parameter line shown on the sheet: the leavening % when the recipe uses one.
  let paramOut = null;
  if (recipe && recipe.leaveningKey && (logic === 'orders' || logic === 'both')) {
    const lev = recipeIngs.find(g => g.key === recipe.leaveningKey);
    paramOut = { label: (lev ? lev.label : 'Leavening') + ' %', value: pct };
  }

  // Divisor (display-only): sum the included lines that have a quantity, then split.
  let divisorOut = null;
  if (divisor && Array.isArray(divisor.includedIds) && divisor.includedIds.length) {
    const incl = lines.filter(it => divisor.includedIds.includes(it.id) && num(it.qty) > 0);
    if (incl.length) {
      const dTotal = incl.reduce((s, it) => s + num(it.qty) * num(it.weightG), 0);
      const dnames = [];
      for (const it of incl) if (!dnames.includes(it.name)) dnames.push(it.name);
      const n = Math.max(0, Math.round(num(divisor.n)));
      divisorOut = { names: dnames, total: Math.round(dTotal), n, result: n > 0 ? Math.round(dTotal / n) : 0 };
    }
  }

  // Crate boxes (display-only): one per line that opted in and has a quantity.
  const crates = [];
  for (const it of lines) {
    const qty = num(it.qty);
    if (qty <= 0 || !it.crate || !it.crate.show) continue;
    const perBox = num(it.crate.perBox);
    if (perBox <= 0) continue;
    crates.push({ name: it.name, count: Math.round((qty / perBox) * 10) / 10, eachBoxG: Math.round(perBox * num(it.weightG)) });
  }

  return {
    dough: recipe ? safeDough(recipe.name) : 'Recipe',
    recipeId: recipe ? recipe.id : '',
    param: paramOut,
    total_g: Math.round(total),
    extra_g: Math.round(extra),
    ingredients,
    divisor: divisorOut,
    crates,
  };
}

// Human-readable grouped text (client header + indented product lines + extra),
// matching the old log text so sharing/preview keep the same look.
export function buildLogText(items, occasional, extra) {
  const lines = [];
  const byClient = new Map();
  const order = [];
  for (const it of (items || [])) {
    if (num(it.qty) <= 0) continue;
    const key = it.clientName || 'Client';
    if (!byClient.has(key)) { byClient.set(key, []); order.push(key); }
    byClient.get(key).push('  ' + it.name + ': ' + num(it.qty) + (it.kind === 'kg' ? ' kg' : ' pz'));
  }
  for (const key of order) {
    lines.push(key + ':');
    lines.push(...byClient.get(key));
  }
  for (const occ of (occasional || [])) {
    const prods = (occ.products || []).filter(p => num(p.qty) > 0);
    if (!prods.length) continue;
    lines.push((occ.name || 'Occasional client') + ':');
    for (const p of prods) lines.push('  ' + p.name + ': ' + num(p.qty) + (p.unit === 'kg' ? ' kg' : ' pz'));
  }
  if (extra && num(extra.grams) > 0) {
    lines.push('Extra dough: ' + (extra.value != null ? extra.value : num(extra.grams)) + ' ' + (extra.unit || 'g'));
  }
  return lines.join('\n');
}

// ── Log lifecycle (append-only) ───────────────────────────────────────────────

// A brand-new log with its first version. Each Confirm makes a NEW log — it never
// overwrites an existing one (the whole point of the new model).
export function createLog({ id, dough, recipeId, forDay, version, createdAtMs, origin }) {
  return {
    id: String(id),
    bakery: 'main',
    dough: safeDough(dough),
    recipeId: String(recipeId || ''),
    forDay: safeForDay(forDay),
    origin: origin === 'manual' ? 'manual' : 'calculator',
    createdAtMs: num(createdAtMs),
    versions: [clone(version)],
  };
}

// The latest (current) version of a log — the last element of the append-only chain.
export function latestVersion(log) {
  const vs = log && Array.isArray(log.versions) ? log.versions : [];
  return vs.length ? vs[vs.length - 1] : null;
}

// Append a new version (an edit). Returns a NEW log object; the previous versions
// are preserved untouched — nothing is ever deleted.
export function addVersion(log, version) {
  const next = clone(log);
  if (!Array.isArray(next.versions)) next.versions = [];
  next.versions.push(clone(version));
  return next;
}

// Change a log's target day (today/tomorrow) without touching its version history.
// Used when an edit re-confirms and the user picks a different Today/Tomorrow.
// Returns a NEW log object (pure); an invalid day keeps the existing one.
export function setForDay(log, forDay) {
  const next = clone(log);
  next.forDay = FOR_DAYS.includes(forDay) ? forDay : next.forDay;
  return next;
}

// Decide whether a calculator Confirm should CREATE a new log or UPDATE an existing
// one. A tab confirms into the SAME log until Reset clears the link; if the linked
// log no longer exists (e.g. it was deleted), fall back to creating a fresh one.
export function confirmTarget({ linkedId, linkedExists }) {
  return (linkedId && linkedExists) ? 'update' : 'create';
}

// Restore a past version: append a COPY of versions[index] on top as a new entry,
// tagged kind:'restore'. History is never truncated — the restored content simply
// becomes the new latest version, with fresh authorship/timestamp.
export function restoreVersion(log, index, { calculatedBy, at }) {
  const vs = log && Array.isArray(log.versions) ? log.versions : [];
  if (index < 0 || index >= vs.length) return clone(log);
  const src = clone(vs[index]);
  src.kind = 'restore';
  src.restoredFrom = index;
  src.calculatedBy = calculatedBy != null ? String(calculatedBy) : (src.calculatedBy || '');
  src.at = at || src.at;
  return addVersion(log, src);
}

// ── Migration from the old model (no log is lost) ─────────────────────────────
// Old model: one record per dough { dough, date, time, text }. Convert each into a
// new single-version log, preserving the text verbatim. Marked legacy:true so the
// read-only view shows the saved text (the old model kept no per-product quantities,
// so a full calculator sheet cannot be reconstructed — the text is the source).
export function migrateOldRecord(record, { id, createdAtMs }) {
  const dough = safeDough(record && record.dough);
  const version = {
    calculatedBy: '',
    at: { date: (record && record.date) || '', time: (record && record.time) || '' },
    kind: 'create',
    legacy: true,
    items: [],
    occasional: [],
    sheet: null,
    text: (record && record.text) || '',
  };
  return createLog({ id, dough, forDay: 'today', version, createdAtMs });
}

export function migrateOldLogs(records, makeId, baseMs = 0) {
  const out = [];
  const list = Array.isArray(records) ? records : [];
  list.forEach((r, i) => {
    out.push(migrateOldRecord(r, { id: makeId(r, i), createdAtMs: baseMs + i }));
  });
  return out;
}

// Filter logs for the app's Log LIST only: keep a log when its dough type is visible
// AND it is still within the retention window (created no more than retentionHours
// ago). DISPLAY-only — the database keeps every log; this never deletes anything.
// Pure (nowMs is passed in) so it can be unit-tested. `visibility` is keyed by the
// lowercase dough name (focaccia/brioche/sourdough); a missing key counts as visible.
export function filterVisibleLogs(logs, { visibility = {}, retentionHours = 24, nowMs = 0 } = {}) {
  const list = Array.isArray(logs) ? logs : [];
  // retentionHours may be a single number (applies to every dough) OR a per-dough
  // map keyed by lowercase dough name (focaccia/brioche/sourdough).
  const hoursFor = (key) => num(
    retentionHours && typeof retentionHours === 'object' ? retentionHours[key] : retentionHours
  );
  return list.filter((log) => {
    // Key by recipe id (new logs) falling back to the dough name (migrated logs).
    const key = String((log && (log.recipeId || log.dough)) || '').toLowerCase();
    if (visibility[key] === false) return false;
    const windowMs = Math.max(0, hoursFor(key)) * 3600 * 1000;
    if (windowMs > 0 && num(nowMs) - num(log && log.createdAtMs) > windowMs) return false;
    return true;
  });
}

// ── Day label (relative to the day it is READ, not the day it was made) ───────
// `forDay` records the day the dough was FOR, chosen at creation — so it is only
// meaningful together with the day the log was created. Rendering it literally
// froze the badge ("Today" stayed "Today" forever); a log made for today must
// read "Yesterday" tomorrow. So resolve the log's TARGET DATE (creation day, +1
// when forDay is 'tomorrow') and name it relative to the current day.
//
// Pure (nowMs is passed in) so it is unit-testable. Returns { text, tone }; tone
// drives the badge colour ('today' | 'tomorrow' | 'past').

// Calendar-day number in LOCAL time. Built from the Y/M/D components rather than
// dividing the timestamp, so a DST change (which makes a day 23 or 25 hours long)
// cannot shift a date by one.
function localDayIndex(ms) {
  const d = new Date(num(ms));
  return Math.floor(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()) / 86400000);
}

export function dayLabel(log, nowMs) {
  const forDay = safeForDay(log && log.forDay);
  const createdAtMs = num(log && log.createdAtMs);

  // A log with no usable creation time (corrupt data) has no anchor to count from;
  // fall back to the literal stored choice rather than inventing a wrong date.
  if (createdAtMs <= 0 || !Number.isFinite(Number(nowMs))) {
    return forDay === 'tomorrow'
      ? { text: 'Tomorrow', tone: 'tomorrow' }
      : { text: 'Today', tone: 'today' };
  }

  const target = localDayIndex(createdAtMs) + (forDay === 'tomorrow' ? 1 : 0);
  const diff = target - localDayIndex(nowMs);

  if (diff === 0) return { text: 'Today', tone: 'today' };
  if (diff === 1) return { text: 'Tomorrow', tone: 'tomorrow' };
  if (diff === -1) return { text: 'Yesterday', tone: 'past' };
  // Beyond ±1 day the log is normally already out of the 24/48h retention window,
  // but a clock change or a long-lived tab can still surface one — name it plainly
  // instead of showing a wrong "Today".
  if (diff > 1) return { text: 'In ' + diff + ' days', tone: 'tomorrow' };
  return { text: -diff + ' days ago', tone: 'past' };
}

// Sort logs for display: newest first by creation time, with a stable id tiebreak.
export function sortLogs(logs) {
  return (Array.isArray(logs) ? logs.slice() : []).sort((a, b) => {
    const d = num(b.createdAtMs) - num(a.createdAtMs);
    return d !== 0 ? d : String(b.id).localeCompare(String(a.id));
  });
}
